//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoCarrierSystem.CJKE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", ConfigurationName="CJKE.AddressSearchWSImpl")]
    public interface AddressSearchWSImpl {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationRequest", ReplyAction="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MangoCarrierSystem.CJKE.getAddressInformationResponse getAddressInformation(MangoCarrierSystem.CJKE.getAddressInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationRequest", ReplyAction="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationResponse")]
        System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationResponse> getAddressInformationAsync(MangoCarrierSystem.CJKE.getAddressInformationRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValueRequest", ReplyAction="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValueResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MangoCarrierSystem.CJKE.getAddressInformationByValueResponse getAddressInformationByValue(MangoCarrierSystem.CJKE.getAddressInformationByValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValueRequest", ReplyAction="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValueResponse")]
        System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValueResponse> getAddressInformationByValueAsync(MangoCarrierSystem.CJKE.getAddressInformationByValueRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValue2Request", ReplyAction="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValue2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MangoCarrierSystem.CJKE.getAddressInformationByValue2Response getAddressInformationByValue2(MangoCarrierSystem.CJKE.getAddressInformationByValue2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValue2Request", ReplyAction="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValue2Response")]
        System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValue2Response> getAddressInformationByValue2Async(MangoCarrierSystem.CJKE.getAddressInformationByValue2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValue3Request", ReplyAction="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValue3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MangoCarrierSystem.CJKE.getAddressInformationByValue3Response getAddressInformationByValue3(MangoCarrierSystem.CJKE.getAddressInformationByValue3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValue3Request", ReplyAction="http://webservice.address.nplus.doortodoor.co.kr/AddressSearchWSImpl/getAddressIn" +
            "formationByValue3Response")]
        System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValue3Response> getAddressInformationByValue3Async(MangoCarrierSystem.CJKE.getAddressInformationByValue3Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/")]
    public partial class addressSearchRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string boxTypField;
        
        private string clntMgmCustCdField;
        
        private string clntNumField;
        
        private string cntrLarcCdField;
        
        private string fareDivField;
        
        private string orderNoField;
        
        private string prngDivCdField;
        
        private string rcvrAddrField;
        
        private string sndprsnAddrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string boxTyp {
            get {
                return this.boxTypField;
            }
            set {
                this.boxTypField = value;
                this.RaisePropertyChanged("boxTyp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clntMgmCustCd {
            get {
                return this.clntMgmCustCdField;
            }
            set {
                this.clntMgmCustCdField = value;
                this.RaisePropertyChanged("clntMgmCustCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clntNum {
            get {
                return this.clntNumField;
            }
            set {
                this.clntNumField = value;
                this.RaisePropertyChanged("clntNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cntrLarcCd {
            get {
                return this.cntrLarcCdField;
            }
            set {
                this.cntrLarcCdField = value;
                this.RaisePropertyChanged("cntrLarcCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fareDiv {
            get {
                return this.fareDivField;
            }
            set {
                this.fareDivField = value;
                this.RaisePropertyChanged("fareDiv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string prngDivCd {
            get {
                return this.prngDivCdField;
            }
            set {
                this.prngDivCdField = value;
                this.RaisePropertyChanged("prngDivCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rcvrAddr {
            get {
                return this.rcvrAddrField;
            }
            set {
                this.rcvrAddrField = value;
                this.RaisePropertyChanged("rcvrAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string sndprsnAddr {
            get {
                return this.sndprsnAddrField;
            }
            set {
                this.sndprsnAddrField = value;
                this.RaisePropertyChanged("sndprsnAddr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/")]
    public partial class addressSearchResponse2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cgostsField;
        
        private string clntMgmCustCdField;
        
        private string clntNumField;
        
        private string dlvClsfCdField;
        
        private string dlvClsfNmField;
        
        private string dlvPreArrBranCdField;
        
        private string dlvPreArrBranNmField;
        
        private string dlvPreArrBranShortNmField;
        
        private string dlvPreArrEmpNickNmField;
        
        private string dlvPreArrEmpNmField;
        
        private string dlvPreArrEmpNumField;
        
        private string dlvSubClsfCdField;
        
        private string errorCdField;
        
        private string errorMsgField;
        
        private string prngDivCdField;
        
        private string rcvrClsfAddrField;
        
        private string rcvrEtcAddrField;
        
        private string rcvrNewAddrField;
        
        private string rcvrNewAddrDtlField;
        
        private string rcvrNewAddrYnField;
        
        private string rcvrOldAddrField;
        
        private string rcvrOldAddrDtlField;
        
        private string rcvrShortAddrField;
        
        private string rcvrZipnumField;
        
        private string rspsDivField;
        
        private int zpidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cgosts {
            get {
                return this.cgostsField;
            }
            set {
                this.cgostsField = value;
                this.RaisePropertyChanged("cgosts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clntMgmCustCd {
            get {
                return this.clntMgmCustCdField;
            }
            set {
                this.clntMgmCustCdField = value;
                this.RaisePropertyChanged("clntMgmCustCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clntNum {
            get {
                return this.clntNumField;
            }
            set {
                this.clntNumField = value;
                this.RaisePropertyChanged("clntNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dlvClsfCd {
            get {
                return this.dlvClsfCdField;
            }
            set {
                this.dlvClsfCdField = value;
                this.RaisePropertyChanged("dlvClsfCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dlvClsfNm {
            get {
                return this.dlvClsfNmField;
            }
            set {
                this.dlvClsfNmField = value;
                this.RaisePropertyChanged("dlvClsfNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dlvPreArrBranCd {
            get {
                return this.dlvPreArrBranCdField;
            }
            set {
                this.dlvPreArrBranCdField = value;
                this.RaisePropertyChanged("dlvPreArrBranCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string dlvPreArrBranNm {
            get {
                return this.dlvPreArrBranNmField;
            }
            set {
                this.dlvPreArrBranNmField = value;
                this.RaisePropertyChanged("dlvPreArrBranNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dlvPreArrBranShortNm {
            get {
                return this.dlvPreArrBranShortNmField;
            }
            set {
                this.dlvPreArrBranShortNmField = value;
                this.RaisePropertyChanged("dlvPreArrBranShortNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string dlvPreArrEmpNickNm {
            get {
                return this.dlvPreArrEmpNickNmField;
            }
            set {
                this.dlvPreArrEmpNickNmField = value;
                this.RaisePropertyChanged("dlvPreArrEmpNickNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string dlvPreArrEmpNm {
            get {
                return this.dlvPreArrEmpNmField;
            }
            set {
                this.dlvPreArrEmpNmField = value;
                this.RaisePropertyChanged("dlvPreArrEmpNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string dlvPreArrEmpNum {
            get {
                return this.dlvPreArrEmpNumField;
            }
            set {
                this.dlvPreArrEmpNumField = value;
                this.RaisePropertyChanged("dlvPreArrEmpNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string dlvSubClsfCd {
            get {
                return this.dlvSubClsfCdField;
            }
            set {
                this.dlvSubClsfCdField = value;
                this.RaisePropertyChanged("dlvSubClsfCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string errorCd {
            get {
                return this.errorCdField;
            }
            set {
                this.errorCdField = value;
                this.RaisePropertyChanged("errorCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string prngDivCd {
            get {
                return this.prngDivCdField;
            }
            set {
                this.prngDivCdField = value;
                this.RaisePropertyChanged("prngDivCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string rcvrClsfAddr {
            get {
                return this.rcvrClsfAddrField;
            }
            set {
                this.rcvrClsfAddrField = value;
                this.RaisePropertyChanged("rcvrClsfAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string rcvrEtcAddr {
            get {
                return this.rcvrEtcAddrField;
            }
            set {
                this.rcvrEtcAddrField = value;
                this.RaisePropertyChanged("rcvrEtcAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string rcvrNewAddr {
            get {
                return this.rcvrNewAddrField;
            }
            set {
                this.rcvrNewAddrField = value;
                this.RaisePropertyChanged("rcvrNewAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string rcvrNewAddrDtl {
            get {
                return this.rcvrNewAddrDtlField;
            }
            set {
                this.rcvrNewAddrDtlField = value;
                this.RaisePropertyChanged("rcvrNewAddrDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string rcvrNewAddrYn {
            get {
                return this.rcvrNewAddrYnField;
            }
            set {
                this.rcvrNewAddrYnField = value;
                this.RaisePropertyChanged("rcvrNewAddrYn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string rcvrOldAddr {
            get {
                return this.rcvrOldAddrField;
            }
            set {
                this.rcvrOldAddrField = value;
                this.RaisePropertyChanged("rcvrOldAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string rcvrOldAddrDtl {
            get {
                return this.rcvrOldAddrDtlField;
            }
            set {
                this.rcvrOldAddrDtlField = value;
                this.RaisePropertyChanged("rcvrOldAddrDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string rcvrShortAddr {
            get {
                return this.rcvrShortAddrField;
            }
            set {
                this.rcvrShortAddrField = value;
                this.RaisePropertyChanged("rcvrShortAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string rcvrZipnum {
            get {
                return this.rcvrZipnumField;
            }
            set {
                this.rcvrZipnumField = value;
                this.RaisePropertyChanged("rcvrZipnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string rspsDiv {
            get {
                return this.rspsDivField;
            }
            set {
                this.rspsDivField = value;
                this.RaisePropertyChanged("rspsDiv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public int zpid {
            get {
                return this.zpidField;
            }
            set {
                this.zpidField = value;
                this.RaisePropertyChanged("zpid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/")]
    public partial class addressSearchRequest2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cgostsField;
        
        private string clntMgmCustCdField;
        
        private string clntNumField;
        
        private string prngDivCdField;
        
        private string rcvrAddrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cgosts {
            get {
                return this.cgostsField;
            }
            set {
                this.cgostsField = value;
                this.RaisePropertyChanged("cgosts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string clntMgmCustCd {
            get {
                return this.clntMgmCustCdField;
            }
            set {
                this.clntMgmCustCdField = value;
                this.RaisePropertyChanged("clntMgmCustCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clntNum {
            get {
                return this.clntNumField;
            }
            set {
                this.clntNumField = value;
                this.RaisePropertyChanged("clntNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string prngDivCd {
            get {
                return this.prngDivCdField;
            }
            set {
                this.prngDivCdField = value;
                this.RaisePropertyChanged("prngDivCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string rcvrAddr {
            get {
                return this.rcvrAddrField;
            }
            set {
                this.rcvrAddrField = value;
                this.RaisePropertyChanged("rcvrAddr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/")]
    public partial class addressSearchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string boxTypField;
        
        private string bscFareField;
        
        private string clntMgmCustCdField;
        
        private string clntNumField;
        
        private string cntrLarcCdField;
        
        private string dealFareField;
        
        private string dlvClsfCdField;
        
        private string dlvClsfNmField;
        
        private string dlvPreArrBranCdField;
        
        private string dlvPreArrBranNmField;
        
        private string dlvPreArrBranShortNmField;
        
        private string dlvPreArrEmpNickNmField;
        
        private string dlvPreArrEmpNmField;
        
        private string dlvPreArrEmpNumField;
        
        private string dlvSubClsfCdField;
        
        private string errorCdField;
        
        private string errorMsgField;
        
        private string fareDivField;
        
        private string ferryFareField;
        
        private string gthClsfCdField;
        
        private string gthClsfNmField;
        
        private string gthPreArrBranCdField;
        
        private string gthPreArrBranNmField;
        
        private string gthPreArrBranShortNmField;
        
        private string gthPreArrEmpNickNmField;
        
        private string gthPreArrEmpNmField;
        
        private string gthPreArrEmpNumField;
        
        private string gthSubClsfCdField;
        
        private string jejuFareField;
        
        private string orderNoField;
        
        private string prngDivCdField;
        
        private string rcvrAddrField;
        
        private string rcvrClsfAddrField;
        
        private string rcvrEtcAddrField;
        
        private string rcvrNewAddrField;
        
        private string rcvrNewAddrDtlField;
        
        private string rcvrNewAddrYnField;
        
        private string rcvrOldAddrField;
        
        private string rcvrOldAddrDtlField;
        
        private string rcvrShortAddrField;
        
        private string rcvrZipnumField;
        
        private string sndprClsfAddrField;
        
        private string sndprEtcAddrField;
        
        private string sndprNewAddrField;
        
        private string sndprNewAddrDtlField;
        
        private string sndprNewAddrYnField;
        
        private string sndprOldAddrField;
        
        private string sndprOldAddrDtlField;
        
        private string sndprShortAddrField;
        
        private string sndprZipnumField;
        
        private string sndprsnAddrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string boxTyp {
            get {
                return this.boxTypField;
            }
            set {
                this.boxTypField = value;
                this.RaisePropertyChanged("boxTyp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string bscFare {
            get {
                return this.bscFareField;
            }
            set {
                this.bscFareField = value;
                this.RaisePropertyChanged("bscFare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string clntMgmCustCd {
            get {
                return this.clntMgmCustCdField;
            }
            set {
                this.clntMgmCustCdField = value;
                this.RaisePropertyChanged("clntMgmCustCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string clntNum {
            get {
                return this.clntNumField;
            }
            set {
                this.clntNumField = value;
                this.RaisePropertyChanged("clntNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cntrLarcCd {
            get {
                return this.cntrLarcCdField;
            }
            set {
                this.cntrLarcCdField = value;
                this.RaisePropertyChanged("cntrLarcCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string dealFare {
            get {
                return this.dealFareField;
            }
            set {
                this.dealFareField = value;
                this.RaisePropertyChanged("dealFare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string dlvClsfCd {
            get {
                return this.dlvClsfCdField;
            }
            set {
                this.dlvClsfCdField = value;
                this.RaisePropertyChanged("dlvClsfCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dlvClsfNm {
            get {
                return this.dlvClsfNmField;
            }
            set {
                this.dlvClsfNmField = value;
                this.RaisePropertyChanged("dlvClsfNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string dlvPreArrBranCd {
            get {
                return this.dlvPreArrBranCdField;
            }
            set {
                this.dlvPreArrBranCdField = value;
                this.RaisePropertyChanged("dlvPreArrBranCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string dlvPreArrBranNm {
            get {
                return this.dlvPreArrBranNmField;
            }
            set {
                this.dlvPreArrBranNmField = value;
                this.RaisePropertyChanged("dlvPreArrBranNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string dlvPreArrBranShortNm {
            get {
                return this.dlvPreArrBranShortNmField;
            }
            set {
                this.dlvPreArrBranShortNmField = value;
                this.RaisePropertyChanged("dlvPreArrBranShortNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string dlvPreArrEmpNickNm {
            get {
                return this.dlvPreArrEmpNickNmField;
            }
            set {
                this.dlvPreArrEmpNickNmField = value;
                this.RaisePropertyChanged("dlvPreArrEmpNickNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string dlvPreArrEmpNm {
            get {
                return this.dlvPreArrEmpNmField;
            }
            set {
                this.dlvPreArrEmpNmField = value;
                this.RaisePropertyChanged("dlvPreArrEmpNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string dlvPreArrEmpNum {
            get {
                return this.dlvPreArrEmpNumField;
            }
            set {
                this.dlvPreArrEmpNumField = value;
                this.RaisePropertyChanged("dlvPreArrEmpNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string dlvSubClsfCd {
            get {
                return this.dlvSubClsfCdField;
            }
            set {
                this.dlvSubClsfCdField = value;
                this.RaisePropertyChanged("dlvSubClsfCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string errorCd {
            get {
                return this.errorCdField;
            }
            set {
                this.errorCdField = value;
                this.RaisePropertyChanged("errorCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string fareDiv {
            get {
                return this.fareDivField;
            }
            set {
                this.fareDivField = value;
                this.RaisePropertyChanged("fareDiv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ferryFare {
            get {
                return this.ferryFareField;
            }
            set {
                this.ferryFareField = value;
                this.RaisePropertyChanged("ferryFare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string gthClsfCd {
            get {
                return this.gthClsfCdField;
            }
            set {
                this.gthClsfCdField = value;
                this.RaisePropertyChanged("gthClsfCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string gthClsfNm {
            get {
                return this.gthClsfNmField;
            }
            set {
                this.gthClsfNmField = value;
                this.RaisePropertyChanged("gthClsfNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string gthPreArrBranCd {
            get {
                return this.gthPreArrBranCdField;
            }
            set {
                this.gthPreArrBranCdField = value;
                this.RaisePropertyChanged("gthPreArrBranCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string gthPreArrBranNm {
            get {
                return this.gthPreArrBranNmField;
            }
            set {
                this.gthPreArrBranNmField = value;
                this.RaisePropertyChanged("gthPreArrBranNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string gthPreArrBranShortNm {
            get {
                return this.gthPreArrBranShortNmField;
            }
            set {
                this.gthPreArrBranShortNmField = value;
                this.RaisePropertyChanged("gthPreArrBranShortNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string gthPreArrEmpNickNm {
            get {
                return this.gthPreArrEmpNickNmField;
            }
            set {
                this.gthPreArrEmpNickNmField = value;
                this.RaisePropertyChanged("gthPreArrEmpNickNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string gthPreArrEmpNm {
            get {
                return this.gthPreArrEmpNmField;
            }
            set {
                this.gthPreArrEmpNmField = value;
                this.RaisePropertyChanged("gthPreArrEmpNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string gthPreArrEmpNum {
            get {
                return this.gthPreArrEmpNumField;
            }
            set {
                this.gthPreArrEmpNumField = value;
                this.RaisePropertyChanged("gthPreArrEmpNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string gthSubClsfCd {
            get {
                return this.gthSubClsfCdField;
            }
            set {
                this.gthSubClsfCdField = value;
                this.RaisePropertyChanged("gthSubClsfCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string jejuFare {
            get {
                return this.jejuFareField;
            }
            set {
                this.jejuFareField = value;
                this.RaisePropertyChanged("jejuFare");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string orderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("orderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string prngDivCd {
            get {
                return this.prngDivCdField;
            }
            set {
                this.prngDivCdField = value;
                this.RaisePropertyChanged("prngDivCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string rcvrAddr {
            get {
                return this.rcvrAddrField;
            }
            set {
                this.rcvrAddrField = value;
                this.RaisePropertyChanged("rcvrAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string rcvrClsfAddr {
            get {
                return this.rcvrClsfAddrField;
            }
            set {
                this.rcvrClsfAddrField = value;
                this.RaisePropertyChanged("rcvrClsfAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string rcvrEtcAddr {
            get {
                return this.rcvrEtcAddrField;
            }
            set {
                this.rcvrEtcAddrField = value;
                this.RaisePropertyChanged("rcvrEtcAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string rcvrNewAddr {
            get {
                return this.rcvrNewAddrField;
            }
            set {
                this.rcvrNewAddrField = value;
                this.RaisePropertyChanged("rcvrNewAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string rcvrNewAddrDtl {
            get {
                return this.rcvrNewAddrDtlField;
            }
            set {
                this.rcvrNewAddrDtlField = value;
                this.RaisePropertyChanged("rcvrNewAddrDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string rcvrNewAddrYn {
            get {
                return this.rcvrNewAddrYnField;
            }
            set {
                this.rcvrNewAddrYnField = value;
                this.RaisePropertyChanged("rcvrNewAddrYn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string rcvrOldAddr {
            get {
                return this.rcvrOldAddrField;
            }
            set {
                this.rcvrOldAddrField = value;
                this.RaisePropertyChanged("rcvrOldAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string rcvrOldAddrDtl {
            get {
                return this.rcvrOldAddrDtlField;
            }
            set {
                this.rcvrOldAddrDtlField = value;
                this.RaisePropertyChanged("rcvrOldAddrDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string rcvrShortAddr {
            get {
                return this.rcvrShortAddrField;
            }
            set {
                this.rcvrShortAddrField = value;
                this.RaisePropertyChanged("rcvrShortAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string rcvrZipnum {
            get {
                return this.rcvrZipnumField;
            }
            set {
                this.rcvrZipnumField = value;
                this.RaisePropertyChanged("rcvrZipnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string sndprClsfAddr {
            get {
                return this.sndprClsfAddrField;
            }
            set {
                this.sndprClsfAddrField = value;
                this.RaisePropertyChanged("sndprClsfAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public string sndprEtcAddr {
            get {
                return this.sndprEtcAddrField;
            }
            set {
                this.sndprEtcAddrField = value;
                this.RaisePropertyChanged("sndprEtcAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string sndprNewAddr {
            get {
                return this.sndprNewAddrField;
            }
            set {
                this.sndprNewAddrField = value;
                this.RaisePropertyChanged("sndprNewAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string sndprNewAddrDtl {
            get {
                return this.sndprNewAddrDtlField;
            }
            set {
                this.sndprNewAddrDtlField = value;
                this.RaisePropertyChanged("sndprNewAddrDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string sndprNewAddrYn {
            get {
                return this.sndprNewAddrYnField;
            }
            set {
                this.sndprNewAddrYnField = value;
                this.RaisePropertyChanged("sndprNewAddrYn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string sndprOldAddr {
            get {
                return this.sndprOldAddrField;
            }
            set {
                this.sndprOldAddrField = value;
                this.RaisePropertyChanged("sndprOldAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string sndprOldAddrDtl {
            get {
                return this.sndprOldAddrDtlField;
            }
            set {
                this.sndprOldAddrDtlField = value;
                this.RaisePropertyChanged("sndprOldAddrDtl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string sndprShortAddr {
            get {
                return this.sndprShortAddrField;
            }
            set {
                this.sndprShortAddrField = value;
                this.RaisePropertyChanged("sndprShortAddr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=49)]
        public string sndprZipnum {
            get {
                return this.sndprZipnumField;
            }
            set {
                this.sndprZipnumField = value;
                this.RaisePropertyChanged("sndprZipnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=50)]
        public string sndprsnAddr {
            get {
                return this.sndprsnAddrField;
            }
            set {
                this.sndprsnAddrField = value;
                this.RaisePropertyChanged("sndprsnAddr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressInformation", WrapperNamespace="http://webservice.address.nplus.doortodoor.co.kr/", IsWrapped=true)]
    public partial class getAddressInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MangoCarrierSystem.CJKE.addressSearchRequest[] arg0;
        
        public getAddressInformationRequest() {
        }
        
        public getAddressInformationRequest(MangoCarrierSystem.CJKE.addressSearchRequest[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressInformationResponse", WrapperNamespace="http://webservice.address.nplus.doortodoor.co.kr/", IsWrapped=true)]
    public partial class getAddressInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getAddressInformationResponse() {
        }
        
        public getAddressInformationResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressInformationByValue", WrapperNamespace="http://webservice.address.nplus.doortodoor.co.kr/", IsWrapped=true)]
    public partial class getAddressInformationByValueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MangoCarrierSystem.CJKE.addressSearchRequest[] arg0;
        
        public getAddressInformationByValueRequest() {
        }
        
        public getAddressInformationByValueRequest(MangoCarrierSystem.CJKE.addressSearchRequest[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressInformationByValueResponse", WrapperNamespace="http://webservice.address.nplus.doortodoor.co.kr/", IsWrapped=true)]
    public partial class getAddressInformationByValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MangoCarrierSystem.CJKE.addressSearchResponse[] @return;
        
        public getAddressInformationByValueResponse() {
        }
        
        public getAddressInformationByValueResponse(MangoCarrierSystem.CJKE.addressSearchResponse[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressInformationByValue2", WrapperNamespace="http://webservice.address.nplus.doortodoor.co.kr/", IsWrapped=true)]
    public partial class getAddressInformationByValue2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MangoCarrierSystem.CJKE.addressSearchRequest arg0;
        
        public getAddressInformationByValue2Request() {
        }
        
        public getAddressInformationByValue2Request(MangoCarrierSystem.CJKE.addressSearchRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressInformationByValue2Response", WrapperNamespace="http://webservice.address.nplus.doortodoor.co.kr/", IsWrapped=true)]
    public partial class getAddressInformationByValue2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MangoCarrierSystem.CJKE.addressSearchResponse @return;
        
        public getAddressInformationByValue2Response() {
        }
        
        public getAddressInformationByValue2Response(MangoCarrierSystem.CJKE.addressSearchResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressInformationByValue3", WrapperNamespace="http://webservice.address.nplus.doortodoor.co.kr/", IsWrapped=true)]
    public partial class getAddressInformationByValue3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MangoCarrierSystem.CJKE.addressSearchRequest2[] arg0;
        
        public getAddressInformationByValue3Request() {
        }
        
        public getAddressInformationByValue3Request(MangoCarrierSystem.CJKE.addressSearchRequest2[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAddressInformationByValue3Response", WrapperNamespace="http://webservice.address.nplus.doortodoor.co.kr/", IsWrapped=true)]
    public partial class getAddressInformationByValue3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.address.nplus.doortodoor.co.kr/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MangoCarrierSystem.CJKE.addressSearchResponse2[] @return;
        
        public getAddressInformationByValue3Response() {
        }
        
        public getAddressInformationByValue3Response(MangoCarrierSystem.CJKE.addressSearchResponse2[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddressSearchWSImplChannel : MangoCarrierSystem.CJKE.AddressSearchWSImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressSearchWSImplClient : System.ServiceModel.ClientBase<MangoCarrierSystem.CJKE.AddressSearchWSImpl>, MangoCarrierSystem.CJKE.AddressSearchWSImpl {
        
        public AddressSearchWSImplClient() {
        }
        
        public AddressSearchWSImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressSearchWSImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressSearchWSImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressSearchWSImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MangoCarrierSystem.CJKE.getAddressInformationResponse MangoCarrierSystem.CJKE.AddressSearchWSImpl.getAddressInformation(MangoCarrierSystem.CJKE.getAddressInformationRequest request) {
            return base.Channel.getAddressInformation(request);
        }
        
        public string getAddressInformation(MangoCarrierSystem.CJKE.addressSearchRequest[] arg0) {
            MangoCarrierSystem.CJKE.getAddressInformationRequest inValue = new MangoCarrierSystem.CJKE.getAddressInformationRequest();
            inValue.arg0 = arg0;
            MangoCarrierSystem.CJKE.getAddressInformationResponse retVal = ((MangoCarrierSystem.CJKE.AddressSearchWSImpl)(this)).getAddressInformation(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationResponse> MangoCarrierSystem.CJKE.AddressSearchWSImpl.getAddressInformationAsync(MangoCarrierSystem.CJKE.getAddressInformationRequest request) {
            return base.Channel.getAddressInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationResponse> getAddressInformationAsync(MangoCarrierSystem.CJKE.addressSearchRequest[] arg0) {
            MangoCarrierSystem.CJKE.getAddressInformationRequest inValue = new MangoCarrierSystem.CJKE.getAddressInformationRequest();
            inValue.arg0 = arg0;
            return ((MangoCarrierSystem.CJKE.AddressSearchWSImpl)(this)).getAddressInformationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MangoCarrierSystem.CJKE.getAddressInformationByValueResponse MangoCarrierSystem.CJKE.AddressSearchWSImpl.getAddressInformationByValue(MangoCarrierSystem.CJKE.getAddressInformationByValueRequest request) {
            return base.Channel.getAddressInformationByValue(request);
        }
        
        public MangoCarrierSystem.CJKE.addressSearchResponse[] getAddressInformationByValue(MangoCarrierSystem.CJKE.addressSearchRequest[] arg0) {
            MangoCarrierSystem.CJKE.getAddressInformationByValueRequest inValue = new MangoCarrierSystem.CJKE.getAddressInformationByValueRequest();
            inValue.arg0 = arg0;
            MangoCarrierSystem.CJKE.getAddressInformationByValueResponse retVal = ((MangoCarrierSystem.CJKE.AddressSearchWSImpl)(this)).getAddressInformationByValue(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValueResponse> MangoCarrierSystem.CJKE.AddressSearchWSImpl.getAddressInformationByValueAsync(MangoCarrierSystem.CJKE.getAddressInformationByValueRequest request) {
            return base.Channel.getAddressInformationByValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValueResponse> getAddressInformationByValueAsync(MangoCarrierSystem.CJKE.addressSearchRequest[] arg0) {
            MangoCarrierSystem.CJKE.getAddressInformationByValueRequest inValue = new MangoCarrierSystem.CJKE.getAddressInformationByValueRequest();
            inValue.arg0 = arg0;
            return ((MangoCarrierSystem.CJKE.AddressSearchWSImpl)(this)).getAddressInformationByValueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MangoCarrierSystem.CJKE.getAddressInformationByValue2Response MangoCarrierSystem.CJKE.AddressSearchWSImpl.getAddressInformationByValue2(MangoCarrierSystem.CJKE.getAddressInformationByValue2Request request) {
            return base.Channel.getAddressInformationByValue2(request);
        }
        
        public MangoCarrierSystem.CJKE.addressSearchResponse getAddressInformationByValue2(MangoCarrierSystem.CJKE.addressSearchRequest arg0) {
            MangoCarrierSystem.CJKE.getAddressInformationByValue2Request inValue = new MangoCarrierSystem.CJKE.getAddressInformationByValue2Request();
            inValue.arg0 = arg0;
            MangoCarrierSystem.CJKE.getAddressInformationByValue2Response retVal = ((MangoCarrierSystem.CJKE.AddressSearchWSImpl)(this)).getAddressInformationByValue2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValue2Response> MangoCarrierSystem.CJKE.AddressSearchWSImpl.getAddressInformationByValue2Async(MangoCarrierSystem.CJKE.getAddressInformationByValue2Request request) {
            return base.Channel.getAddressInformationByValue2Async(request);
        }
        
        public System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValue2Response> getAddressInformationByValue2Async(MangoCarrierSystem.CJKE.addressSearchRequest arg0) {
            MangoCarrierSystem.CJKE.getAddressInformationByValue2Request inValue = new MangoCarrierSystem.CJKE.getAddressInformationByValue2Request();
            inValue.arg0 = arg0;
            return ((MangoCarrierSystem.CJKE.AddressSearchWSImpl)(this)).getAddressInformationByValue2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MangoCarrierSystem.CJKE.getAddressInformationByValue3Response MangoCarrierSystem.CJKE.AddressSearchWSImpl.getAddressInformationByValue3(MangoCarrierSystem.CJKE.getAddressInformationByValue3Request request) {
            return base.Channel.getAddressInformationByValue3(request);
        }
        
        public MangoCarrierSystem.CJKE.addressSearchResponse2[] getAddressInformationByValue3(MangoCarrierSystem.CJKE.addressSearchRequest2[] arg0) {
            MangoCarrierSystem.CJKE.getAddressInformationByValue3Request inValue = new MangoCarrierSystem.CJKE.getAddressInformationByValue3Request();
            inValue.arg0 = arg0;
            MangoCarrierSystem.CJKE.getAddressInformationByValue3Response retVal = ((MangoCarrierSystem.CJKE.AddressSearchWSImpl)(this)).getAddressInformationByValue3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValue3Response> MangoCarrierSystem.CJKE.AddressSearchWSImpl.getAddressInformationByValue3Async(MangoCarrierSystem.CJKE.getAddressInformationByValue3Request request) {
            return base.Channel.getAddressInformationByValue3Async(request);
        }
        
        public System.Threading.Tasks.Task<MangoCarrierSystem.CJKE.getAddressInformationByValue3Response> getAddressInformationByValue3Async(MangoCarrierSystem.CJKE.addressSearchRequest2[] arg0) {
            MangoCarrierSystem.CJKE.getAddressInformationByValue3Request inValue = new MangoCarrierSystem.CJKE.getAddressInformationByValue3Request();
            inValue.arg0 = arg0;
            return ((MangoCarrierSystem.CJKE.AddressSearchWSImpl)(this)).getAddressInformationByValue3Async(inValue);
        }
    }
}
